version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels: ["type: dependencies"]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels: ["type: dependencies"]

  - package-ecosystem: npm
    directory: /sdk/typescript
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    labels: ["type: dependencies"]
    groups:
      sdk-dev-dependencies:
        dependency-type: development
