/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List requests
         * @description Lists requests, newest first. All filters are combined with AND.
         */
        get: operations["listRequests"];
        put?: never;
        /**
         * Enqueue a request
         * @description Queues an outbound request for delivery and returns immediately.
         *
         *     If `dedupe_key` is set and a request with the same key already exists for the same upstream
         *     (within the dedupe window, 24 hours by default), no new request is created. The existing request
         *     is returned with status `200` and the `Hookyard-Deduplicated: true` header. This makes it
         *     safe for applications to retry the enqueue call itself.
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /** Get a request */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        /**
         * List delivery attempts
         * @description Returns every delivery attempt of a request, oldest first.
         */
        get: operations["listAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay a request
         * @description Queues a finished request (`dead`, `succeeded`, `canceled` or `unknown`) for delivery again with a
         *     fresh retry budget. Previous attempts are kept. Replaying a request that is still in progress
         *     returns `409`.
         */
        post: operations["replayRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a request
         * @description Cancels a request that has not finished (`scheduled`, `pending` or `failed`). A request that is
         *     `in_flight` cannot be canceled, because the call to the upstream may already have been sent.
         */
        post: operations["cancelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summarize the dead-letter queue
         * @description Groups dead requests by upstream and failure reason. Use `GET /v1/requests?status=dead` to list
         *     the individual requests.
         */
        get: operations["getDLQSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dlq/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay dead requests in bulk
         * @description Queues every dead request that matches the filter for delivery again. Filters are combined with
         *     AND. An empty filter matches the whole DLQ, so use `dry_run` first to see how many requests
         *     would be replayed. The operation is idempotent: requests that were already replayed are no
         *     longer dead and are not matched again.
         */
        post: operations["replayDLQ"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upstreams */
        get: operations["listUpstreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/upstreams/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upstream name. */
                name: components["schemas"]["UpstreamName"];
            };
            cookie?: never;
        };
        /**
         * Get an upstream
         * @description Returns the effective configuration of an upstream. Secret values are never returned.
         */
        get: operations["getUpstream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-upstream health overview */
        get: operations["getStatsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delivery metrics over time */
        get: operations["getStatsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether every dependency (such as the database) is reachable.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Unique request ID, prefixed with `req_`.
         * @example req_01J9ZK3Q4W5E6R7T8Y9U0I1O2P
         */
        RequestId: string;
        /**
         * @description Name of a configured upstream.
         * @example courier-x
         */
        UpstreamName: string;
        /**
         * @description A duration with a unit (`ms`, `s`, `m`, `h`), for example `"30s"` or `"1h30m"`.
         * @example 30s
         */
        Duration: string;
        /** @enum {string} */
        HTTPMethod: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
        /**
         * @description HTTP headers. Header names are case-insensitive.
         * @example {
         *       "X-Correlation-Id": "7f3c1e"
         *     }
         */
        Headers: {
            [key: string]: string;
        };
        /**
         * @description Free-form labels for filtering and grouping, for example the calling app or tenant.
         *     Up to 20 tags; keys up to 64 characters, values up to 256 characters.
         * @example {
         *       "app": "orders",
         *       "tenant": "acme"
         *     }
         */
        Tags: {
            [key: string]: string;
        };
        /**
         * @description - `scheduled`: waiting for `deliver_at`
         *     - `pending`: waiting to be picked up by a worker
         *     - `in_flight`: being delivered right now
         *     - `failed`: the last attempt failed and a retry is scheduled (see `next_attempt_at`)
         *     - `succeeded`: delivered successfully (final)
         *     - `dead`: retries exhausted or a permanent error; in the DLQ (final)
         *     - `unknown`: the outcome is uncertain, for example a timeout on a non-idempotent call (final;
         *       reserved for v0.2)
         *     - `canceled`: canceled before delivery (final)
         * @enum {string}
         */
        RequestStatus: "scheduled" | "pending" | "in_flight" | "failed" | "succeeded" | "dead" | "unknown" | "canceled";
        /**
         * @description Named retry policy:
         *
         *     | Preset | Attempts | Initial interval | Max interval | Max age |
         *     | --- | --- | --- | --- | --- |
         *     | `none` | 1 | – | – | – |
         *     | `quick` | 5 | 1s | 30s | 10m |
         *     | `standard` | 10 | 5s | 10m | 24h |
         *     | `patient` | 25 | 30s | 1h | 72h |
         * @default standard
         * @enum {string}
         */
        RetryPreset: "none" | "quick" | "standard" | "patient";
        /**
         * @description A custom retry policy. Unset fields come from `preset` (if set), then from the upstream's
         *     policy. Delays grow exponentially and use full jitter:
         *     `delay = random(0, min(max_interval, initial_interval * multiplier^(attempt-1)))`.
         *     A `Retry-After` header from the upstream always takes precedence.
         * @example {
         *       "preset": "standard",
         *       "max_attempts": 5,
         *       "max_interval": "2m"
         *     }
         */
        RetryPolicyObject: {
            preset?: components["schemas"]["RetryPreset"];
            /** @description Total attempts including the first one. */
            max_attempts?: number;
            initial_interval?: components["schemas"]["Duration"];
            max_interval?: components["schemas"]["Duration"];
            multiplier?: number;
            /**
             * @description Give up (move to the DLQ) once this much time has passed since the request became due: its
             *     creation time, or `deliver_at` for scheduled requests.
             */
            max_age?: components["schemas"]["Duration"];
        };
        /** @description A retry preset name, or a custom policy. */
        RetryPolicy: components["schemas"]["RetryPreset"] | components["schemas"]["RetryPolicyObject"];
        /** @description A fully resolved retry policy. */
        EffectiveRetryPolicy: {
            preset?: components["schemas"]["RetryPreset"];
            max_attempts: number;
            initial_interval: components["schemas"]["Duration"];
            max_interval: components["schemas"]["Duration"];
            multiplier: number;
            max_age: components["schemas"]["Duration"];
        };
        CreateRequest: {
            upstream: components["schemas"]["UpstreamName"];
            method: components["schemas"]["HTTPMethod"];
            /**
             * @description Path (and optional query string) appended to the upstream's base URL.
             * @example /shipments?notify=true
             */
            path: string;
            /**
             * @description Headers for this request. Headers configured on the upstream (typically credentials) take
             *     precedence. `Host`, `Content-Length` and hop-by-hop headers can't be set.
             */
            headers?: components["schemas"]["Headers"];
            /**
             * @description Request body. A JSON object, array, number or boolean is sent as JSON with
             *     `Content-Type: application/json`. A string is sent verbatim, so set a `Content-Type` header
             *     for other formats (for example XML or form data). Omit it, or use `null`, to send no body.
             */
            body?: unknown;
            /**
             * @description Makes enqueueing idempotent. While a request with the same key exists for the same upstream
             *     (within the dedupe window), enqueueing again returns that request instead of creating a new
             *     one.
             * @example order-123-create-shipment
             */
            dedupe_key?: string;
            /**
             * Format: date-time
             * @description Deliver no earlier than this time. The request stays `scheduled` until then.
             */
            deliver_at?: string;
            /** @description Per-attempt timeout. Overrides the upstream's timeout. */
            timeout?: components["schemas"]["Duration"];
            retry?: components["schemas"]["RetryPolicy"];
            tags?: components["schemas"]["Tags"];
        };
        Request: {
            id: components["schemas"]["RequestId"];
            upstream: components["schemas"]["UpstreamName"];
            method: components["schemas"]["HTTPMethod"];
            /** @example /shipments */
            path: string;
            headers?: components["schemas"]["Headers"];
            /** @description The body as it was enqueued. */
            body?: unknown;
            dedupe_key?: string | null;
            status: components["schemas"]["RequestStatus"];
            /** @description Number of attempts made so far. */
            attempt_count: number;
            retry: components["schemas"]["EffectiveRetryPolicy"];
            timeout?: components["schemas"]["Duration"];
            tags: components["schemas"]["Tags"];
            /** Format: date-time */
            deliver_at?: string | null;
            /**
             * Format: date-time
             * @description When the next attempt is due, for `scheduled`, `pending` and `failed` requests.
             */
            next_attempt_at?: string | null;
            /** @description Why the most recent attempt failed, if it did. */
            last_error?: components["schemas"]["DeliveryError"] | null;
            /** @description HTTP status code of the most recent response, if any. */
            last_status_code?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description When the request reached a final state.
             */
            completed_at?: string | null;
        };
        RequestList: {
            data: components["schemas"]["Request"][];
            /** @description Cursor for the next page, or `null` on the last page. */
            next_cursor: string | null;
        };
        /**
         * @description - `timeout`: no response within the attempt timeout
         *     - `connection`: DNS, TCP or TLS failure
         *     - `http_status`: the upstream responded with a status classified as a failure
         *     - `max_age_exceeded`: the request's `max_age` passed before it could be delivered
         *     - `canceled`: the request was canceled
         *     - `internal`: an unexpected error inside Hookyard
         * @enum {string}
         */
        DeliveryErrorCode: "timeout" | "connection" | "http_status" | "max_age_exceeded" | "canceled" | "internal";
        DeliveryError: {
            code: components["schemas"]["DeliveryErrorCode"];
            /** @example upstream responded with 503 Service Unavailable */
            message: string;
        };
        Attempt: {
            /** @description 1 for the first attempt. */
            number: number;
            /** Format: date-time */
            started_at: string;
            duration_ms: number;
            /**
             * @description How Hookyard classified the attempt.
             * @enum {string}
             */
            outcome: "success" | "retryable_failure" | "permanent_failure";
            status_code?: number | null;
            error?: components["schemas"]["DeliveryError"] | null;
            response?: components["schemas"]["AttemptResponse"] | null;
            /**
             * Format: date-time
             * @description When the next attempt was scheduled after this one failed, if any.
             */
            retry_at?: string | null;
        };
        AttemptResponse: {
            headers: components["schemas"]["Headers"];
            /** @description The response body, truncated to the configured limit (64 KiB by default). */
            body: string;
            body_truncated: boolean;
        };
        AttemptList: {
            data: components["schemas"]["Attempt"][];
        };
        DLQGroup: {
            upstream: components["schemas"]["UpstreamName"];
            error_code: components["schemas"]["DeliveryErrorCode"];
            /** @description The final HTTP status code, for `http_status` errors. */
            status_code?: number | null;
            count: number;
            /** Format: date-time */
            oldest_dead_at: string;
            /** Format: date-time */
            newest_dead_at: string;
        };
        DLQSummary: {
            /** @description Total number of dead requests matching the filter. */
            total: number;
            groups: components["schemas"]["DLQGroup"][];
        };
        DLQReplayRequest: {
            upstream?: components["schemas"]["UpstreamName"];
            error_code?: components["schemas"]["DeliveryErrorCode"];
            status_code?: number;
            /** Format: date-time */
            dead_after?: string;
            /** Format: date-time */
            dead_before?: string;
            /** @description Only replay these requests. */
            ids?: components["schemas"]["RequestId"][];
            /**
             * @description Count matching requests without replaying them.
             * @default false
             */
            dry_run: boolean;
        };
        DLQReplayResult: {
            /** @description Dead requests that matched the filter. */
            matched: number;
            /** @description Requests queued again (0 for a dry run). */
            replayed: number;
            dry_run: boolean;
        };
        Upstream: {
            name: components["schemas"]["UpstreamName"];
            /**
             * Format: uri
             * @example https://api.courier-x.example
             */
            base_url: string;
            timeout: components["schemas"]["Duration"];
            retry: components["schemas"]["EffectiveRetryPolicy"];
            /**
             * @description Names of headers added to every request. Values are not returned because they often contain secrets.
             * @example [
             *       "Authorization",
             *       "X-Api-Version"
             *     ]
             */
            header_names: string[];
        };
        UpstreamList: {
            data: components["schemas"]["Upstream"][];
        };
        UpstreamStats: {
            upstream: components["schemas"]["UpstreamName"];
            /** @description Requests delivered successfully in the window. */
            succeeded: number;
            /** @description Attempts that failed in the window (including ones that were retried). */
            failed_attempts: number;
            /** @description Requests that moved to the DLQ in the window. */
            dead: number;
            /** @description `succeeded / (succeeded + dead)` for the window, from 0 to 1, or `null` with no finished requests. */
            success_rate: number | null;
            /** @description Attempts per minute, averaged over the window. */
            throughput_per_min: number;
            latency_ms: components["schemas"]["LatencyPercentiles"];
            /** @description Requests currently `pending` or `failed` (waiting to be delivered). */
            queue_depth: number;
            /** @description Age of the oldest request waiting to be delivered. */
            oldest_pending_age_seconds: number | null;
            /** @description Requests currently in the DLQ. */
            dlq_size: number;
        };
        /** @description Attempt latency percentiles in milliseconds, `null` when there were no attempts. */
        LatencyPercentiles: {
            p50: number | null;
            p95: number | null;
            p99: number | null;
        };
        StatsOverview: {
            window: components["schemas"]["Duration"];
            data: components["schemas"]["UpstreamStats"][];
        };
        StatsBucket: {
            /** Format: date-time */
            start: string;
            succeeded: number;
            failed_attempts: number;
            dead: number;
            latency_ms: components["schemas"]["LatencyPercentiles"];
        };
        StatsTimeseries: {
            /** @description The upstream, or `null` for all upstreams combined. */
            upstream?: components["schemas"]["UpstreamName"] | null;
            step: components["schemas"]["Duration"];
            data: components["schemas"]["StatsBucket"][];
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "fail";
            checks: {
                /** @example database */
                name: string;
                /** @enum {string} */
                status: "ok" | "fail";
                error?: string;
            }[];
        };
        /**
         * @description Stable, machine-readable error code.
         * @enum {string}
         */
        ErrorCode: "bad_request" | "unauthorized" | "not_found" | "invalid_state" | "payload_too_large" | "validation_failed" | "unknown_upstream" | "internal";
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Human-readable explanation. Do not parse it; use `code`. */
                message: string;
                /** @description Per-field problems, for `validation_failed`. */
                details?: {
                    /**
                     * @description Dotted path of the invalid field.
                     * @example retry.max_attempts
                     */
                    field: string;
                    message: string;
                }[];
            };
        };
    };
    responses: {
        /**
         * @description The request is malformed: invalid JSON, unknown fields or bad query parameters. Request
         *     bodies are always parsed as JSON, whatever the `Content-Type` header says.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "bad_request",
                 *         "message": "invalid query parameter \"limit\": must be between 1 and 200"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The bearer token is missing or invalid. */
        Unauthorized: {
            headers: {
                /** @description Always `Bearer realm="hookyard"`. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "missing or invalid bearer token"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "request \"req_01J9ZK3Q4W5E6R7T8Y9U0I1O2P\" not found"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource is not in a state that allows this action. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_state",
                 *         "message": "cannot cancel a request that is in_flight"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body exceeds the configured limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "payload_too_large",
                 *         "message": "request body exceeds 1 MiB"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is well formed but fails validation. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "internal",
                 *         "message": "internal server error"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Request ID. */
        RequestId: components["schemas"]["RequestId"];
        /** @description Only include this upstream. */
        Upstream: components["schemas"]["UpstreamName"];
        /** @description Only include requests created at or after this time. */
        CreatedAfter: string;
        /** @description Only include requests created before this time. */
        CreatedBefore: string;
        /** @description Maximum number of items to return. */
        Limit: number;
        /** @description Opaque cursor from a previous response's `next_cursor`. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRequests: {
        parameters: {
            query?: {
                /** @description Only include this upstream. */
                upstream?: components["parameters"]["Upstream"];
                /**
                 * @description Filter by one or more statuses, comma separated.
                 * @example [
                 *       "dead",
                 *       "failed"
                 *     ]
                 */
                status?: components["schemas"]["RequestStatus"][];
                /**
                 * @description Filter by tag, as `key:value`. Repeat the parameter to match several tags.
                 * @example [
                 *       "app:orders"
                 *     ]
                 */
                tag?: string[];
                /** @description Filter by exact dedupe key. */
                dedupe_key?: string;
                /** @description Only include requests created at or after this time. */
                created_after?: components["parameters"]["CreatedAfter"];
                /** @description Only include requests created before this time. */
                created_before?: components["parameters"]["CreatedBefore"];
                /** @description Maximum number of items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous response's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["InternalError"];
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description A request with the same `dedupe_key` already exists; it is returned unchanged. */
            200: {
                headers: {
                    /** @description Always `true` for this response. */
                    "Hookyard-Deduplicated"?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            /** @description The request was queued. */
            202: {
                headers: {
                    /** @description URL of the created request. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["InternalError"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["InternalError"];
        };
    };
    listAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attempts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["InternalError"];
        };
    };
    replayRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was queued again. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["InternalError"];
        };
    };
    cancelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Request ID. */
                id: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was canceled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["InternalError"];
        };
    };
    getDLQSummary: {
        parameters: {
            query?: {
                /** @description Only include this upstream. */
                upstream?: components["parameters"]["Upstream"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DLQ groups, largest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DLQSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["InternalError"];
        };
    };
    replayDLQ: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DLQReplayRequest"];
            };
        };
        responses: {
            /** @description The replay result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DLQReplayResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["InternalError"];
        };
    };
    listUpstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All configured upstreams, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["InternalError"];
        };
    };
    getUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upstream name. */
                name: components["schemas"]["UpstreamName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The upstream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["InternalError"];
        };
    };
    getStatsOverview: {
        parameters: {
            query?: {
                /** @description How far back to aggregate. */
                window?: components["schemas"]["Duration"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per upstream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["InternalError"];
        };
    };
    getStatsTimeseries: {
        parameters: {
            query?: {
                /** @description Only include this upstream. */
                upstream?: components["parameters"]["Upstream"];
                /** @description Start of the range. Defaults to one hour before `to`. */
                from?: string;
                /** @description End of the range. Defaults to now. */
                to?: string;
                /**
                 * @description Bucket size, rounded up to whole minutes. Buckets start at `from` (rounded down to the
                 *     minute). A range may have at most 1500 buckets.
                 */
                step?: components["schemas"]["Duration"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Time buckets, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsTimeseries"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["InternalError"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one dependency check failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
