// Generates src/generated/openapi.ts from the OpenAPI specification.
//
//   node scripts/generate.mjs          write the file
//   node scripts/generate.mjs --check  fail if the committed file is out of date
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const spec = new URL("../../../api/openapi.yaml", import.meta.url);
const target = new URL("../src/generated/openapi.ts", import.meta.url);
const check = process.argv.includes("--check");

const header = `/**
 * Wire types for the Hookyard HTTP API, generated from api/openapi.yaml by openapi-typescript.
 *
 * Do not edit this file by hand. Run \`pnpm generate\` after changing the specification.
 */

`;

const ast = await openapiTS(spec, { alphabetize: false });
const generated = header + astToString(ast);

if (check) {
  let current = "";
  try {
    current = await readFile(target, "utf8");
  } catch {
    // Missing file: reported below.
  }
  if (current !== generated) {
    console.error(
      `${fileURLToPath(target)} is out of date with api/openapi.yaml.\n` +
        "Run `pnpm generate` in sdk/typescript and commit the result.",
    );
    process.exit(1);
  }
  console.log("Generated types are up to date.");
} else {
  await mkdir(new URL(".", target), { recursive: true });
  await writeFile(target, generated);
  console.log(`Wrote ${fileURLToPath(target)}`);
}
